name: logistics-deployment

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: https://github.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Setup and Cloning Repository
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./key.pem
          chmod 600 ./key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -T <<EOF
          REPO_DIR=~/logistics
          echo "Removing existing repository directory if exists"
          rm -rf \$REPO_DIR
          echo "Cloning repository from the relevant branch"
          git clone --single-branch --branch ${{ github.ref_name }} https://github.com/ONDC-Official/Logistics-supply-demand-analysis.git \$REPO_DIR
          EOF

      - name: Install Docker Compose (if not installed)
        run: |
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          # Check if Docker Compose is installed
          if ! command -v docker-compose &> /dev/null
          then
            echo "Docker Compose not found. Installing..."
            sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose is already installed."
          fi
          EOF

      - name: Write secrets to .env on EC2
        run: |
          echo "Writing secrets to .env file"
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          REPO_DIR=~/logistics
          echo "Writing environment variables to .env file"
          echo "FLASK_DEBUG=True" >> \$REPO_DIR/.env
          echo "FLASK_RUN_HOST=0.0.0.0" >> \$REPO_DIR/.env
          echo "FLASK_RUN_PORT=${{ vars.FLASK_RUN_PORT }}" >> \$REPO_DIR/.env
          echo "GEOJSON_FILE=${{ vars.GEOJSON_FILE }}" >> \$REPO_DIR/.env
          echo "CSV_FILE_PATH=${{vars.CSV_FILE_PATH}}" >> \$REPO_DIR/.env
          echo "GEOJSON_FILE_PATH=${{vars.GEOJSON_FILE}}" >> \$REPO_DIR/.env
          

          echo "MONGO_DB_NAME=${{ vars.MONGO_DB_NAME }}" >> \$REPO_DIR/.env
          echo "MONGO_URI=${{vars.MONGO_URI}}" >> \$REPO_DIR/.env
          echo "MONGO_COLLECTION_NAME=${{ vars.MONGO_COLLECTION_NAME }}" >> \$REPO_DIR/.env

          # Ingestion Configuration
          echo "CHUNK_SIZE=100000" >> \$REPO_DIR/.env
          echo "BATCH_SIZE=10000" >> \$REPO_DIR/.env
          echo "MAX_CHUNKS=55" >> \$REPO_DIR/.env
          echo "MIN_RECORDS_FOR_SKIP=200000" >> \$REPO_DIR/.env
          
          # H3 Configuration
          echo "H3_RESOLUTIONS=6,7,8,9,10" >> \$REPO_DIR/.env
          echo "DEFAULT_H3_RESOLUTION=8" >> \$REPO_DIR/.env
          
          # API Configuration
          echo "DEFAULT_HEXAGON_LIMIT=3000" >> \$REPO_DIR/.env
          echo "DEFAULT_SUPPLY_POINT_LIMIT=3000" >> \$REPO_DIR/.env
          
          # Gunicorn Configuration (for production)
          echo "GUNICORN_WORKERS=4" >> \$REPO_DIR/.env
          echo "GUNICORN_THREADS=2" >> \$REPO_DIR/.env
          echo "GUNICORN_TIMEOUT=120" >> \$REPO_DIR/.env
          EOF

      - name: Verify .env and docker-compose.yml files
        run: |
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          REPO_DIR=~/logistics
          # Check if .env and docker-compose.yml files exist
          if [ ! -f \$REPO_DIR/.env ]; then
            echo ".env file not found in \$REPO_DIR!"
            exit 1
          fi
          if [ ! -f \$REPO_DIR/docker-compose.yml ]; then
            echo "docker-compose.yml file not found in \$REPO_DIR!"
            exit 1
          fi
          echo ".env and docker-compose.yml files found."
          EOF

      - name: Automation Mock Server Deployment
        run: |
          echo "Deploying with Docker Compose"
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          REPO_DIR=~/logistics
          cd \$REPO_DIR

          # Ensure the .env and docker-compose.yml files exist
          if [ ! -f .env ]; then
            echo ".env file not found!"
            exit 1
          fi

          if [ ! -f docker-compose.yml ]; then
            echo "docker-compose.yml file not found!"
            exit 1
          fi

          # Start the containers using Docker Compose
          echo "Running docker-compose up -d --build"
          sudo docker compose up -d --build
          EOF
